config/routes.rb
Erp::Newsletters::Engine.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
		namespace :backend, module: "backend", path: "backend/newsletters" do
      resources :newsletters do
        collection do
          post 'list'
          delete 'delete_all'
        end
      end
    end
  end
end

app/models/erp/newsletters/application_record.rb
module Erp::Newsletters
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/erp/newsletters/newsletter.rb
module Erp::Newsletters
  class Newsletter < ApplicationRecord
    validates :email, :presence => true, :uniqueness => true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
    
    # Filters
    def self.filter(query, params)
      params = params.to_unsafe_hash
      and_conds = []
      
      # show archived items condition - default: false
			show_archived = false
			
			#filters
			if params["filters"].present?
				params["filters"].each do |ft|
					or_conds = []
					ft[1].each do |cond|
						# in case filter is show archived
						if cond[1]["name"] == 'show_archived'
							# show archived items
							show_archived = true
						else
							or_conds << "#{cond[1]["name"]} = '#{cond[1]["value"]}'"
						end
					end
					and_conds << '('+or_conds.join(' OR ')+')' if !or_conds.empty?
				end
			end
      
      #keywords
      if params["keywords"].present?
        params["keywords"].each do |kw|
          or_conds = []
          kw[1].each do |cond|
            or_conds << "LOWER(#{cond[1]["name"]}) LIKE '%#{cond[1]["value"].downcase.strip}%'"
          end
          and_conds << '('+or_conds.join(' OR ')+')'
        end
      end

      query = query.where(and_conds.join(' AND ')) if !and_conds.empty?
      
      return query
    end
    
    def self.search(params)
      query = self.all
      query = self.filter(query, params)
      
      # order
      if params[:sort_by].present?
        order = params[:sort_by]
        order += " #{params[:sort_direction]}" if params[:sort_direction].present?
        
        query = query.order(order)
      end
      
      return query
    end
  end
end

app/controllers/erp/newsletters/backend/newsletters_controller.rb
module Erp
  module Newsletters
    module Backend
      class NewslettersController < Erp::Backend::BackendController
        before_action :set_newsletter, only: [:show, :edit, :update, :destroy]
        before_action :set_newsletters, only: [:delete_all]
    
        # GET /newsletters
        def index
        end
    
        # GET /newsletters
        def list
          @newsletters = Newsletter.search(params).paginate(:page => params[:page], :per_page => 50)
          
          render layout: nil
        end
    
        # GET /newsletters/new
        def new
          @newsletter = Newsletter.new
        end
    
        # GET /newsletters/1/edit
        def edit
        end
    
        # POST /newsletters
        def create
          @newsletter = Newsletter.new(newsletter_params)
    
          if @newsletter.save
            redirect_to @newsletter, notice: 'Newsletter was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /newsletters/1
        def update
          if @newsletter.update(newsletter_params)
            if request.xhr?
              render json: {
                status: 'success',
                text: @newsletter.id,
                value: @newsletter.email
              }              
            else
              redirect_to erp_newsletters.edit_backend_newsletter_path(@newsletter), notice: t('.success')
            end
          else
            render :edit
          end
        end
    
        # DELETE /newsletters/1
        def destroy
          @newsletter.destroy
          
          respond_to do |format|
            format.html { redirect_to erp_newsletters.backend_newsletters_path, notice: t('.success') }
            format.json {
              render json: {
                'message': t('.success'),
                'type': 'success'
              }
            }
          end
        end
        
        # DELETE /newsletters/delete_all?ids=1,2,3
        def delete_all         
          @newsletters.destroy_all
          
          respond_to do |format|
            format.json {
              render json: {
                'message': t('.success'),
                'type': 'success'
              }
            }
          end          
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_newsletter
            @newsletter = Newsletter.find(params[:id])
          end
          
          def set_newsletters
            @newsletters = Newsletter.where(id: params[:ids])
          end
    
          # Only allow a trusted parameter "white list" through.
          def newsletter_params
            params.fetch(:newsletter, {}).permit(:email)
          end
      end
    end
  end
end

app/controllers/erp/newsletters/frontend/newsletters_controller.rb
module Erp
  module Newsletters
    module Frontend
      class NewslettersController < Erp::Frontend::FrontendController
        def add_email_to_newsletter
          @newsletter = Erp::Newsletters::Newsletter.new(newsletter_params)
  
          if @newsletter.save
            render json: {
              status: 'success',
              message: 'Cảm ơn bạn đã đăng ký nhận bản tin.'
            }
          else
            render json: {
              status: 'warning',
              message: 'Email này đã được đăng ký hoặc nhập sai định dạng.'
            }
          end
        end
        
        private
        # Use callbacks to share common setup or constraints between actions.
        def set_newsletter
          @newsletter = Erp::Newsletters::Newsletter.find(params[:id])
        end
  
        # Only allow a trusted parameter "white list" through.
        def newsletter_params
          params.fetch(:newsletter, {}).permit(:email)
        end
      end
    end
  end
end
      

app/helpers/erp/newsletters/application_helper.rb
module Erp
  module Newsletters
    module ApplicationHelper
    end
  end
end

app/views/erp/newsletters/backend/newsletters/_form.html.erb
<%= form_for(newsletter) do |f| %>
  <% if newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/erp/newsletters/backend/newsletters/edit.html.erb
<h1>Editing Newsletter</h1>

<%= render 'form', newsletter: @newsletter %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/erp/newsletters/backend/newsletters/index.html.erb
<% content_for :title do %>
    <%= t('.newsletters') %>
<% end %>

<% content_for :page_title do %>
    <i class="fa fa-archive"></i> <%= t('.newsletters') %>
<% end %>

<%= erp_datalist(
    url: erp_newsletters.list_backend_newsletters_path,
    keywords: [
        {
            text: t('.email'), name: 'erp_newsletters_newsletters.email'
        }
    ],
    actions: [
        {
            text: '<i class="fa fa-trash"></i> '+t('.delete'),
            url: erp_newsletters.delete_all_backend_newsletters_path,
            data_method: 'DELETE',
            data_confirm: t('.delete_confirm')
        }
    ],
    filters: [
        
    ],
    columns: [
        {
            text: t('.email'), name: 'email', value: true, checked: true
        },
        {
            text: t('.created_at'), name: 'created_at', value: true, checked: true
        }
    ],
    sort: { sort_by: 'erp_newsletters_newsletters.created_at', sort_direction: 'desc' }
) %>    

app/views/erp/newsletters/backend/newsletters/list.html.erb
<div class="">
    <table class="table table-advance table-hover table-striped table-checkable order-column" id="">
        <thead>
            <tr>
                <th width='1%'>
                    <%= erp_datalist_check_all %>
                </th>
                <% if get_columns(params).include?("email") %>
                    <th class="sortable" sort-by='erp_newsletters_newsletters.email'>
                        <%= t('.email') %>
                    </th>
                <% end %>
                <% if get_columns(params).include?("created_at") %>
                    <th class="sortable" sort-by='erp_newsletters_newsletters.created_at'>
                        <%= t('.created_at') %>
                    </th>
                <% end %>
                <th width="7%"><%= t('.actions') %></th>
            </tr>
        </thead>
        <tbody>
            <% @newsletters.each do |newsletter| %>
                <tr class="odd gradeX">
                    <td>
                        <%= erp_datalist_check_row(id: newsletter.id) %>
                    </td>
                    <% if get_columns(params).include?("email") %>
                        <td><%= newsletter.email %></td>
                    <% end %>
                    <% if get_columns(params).include?("created_at") %>
                        <td><%= newsletter.created_at.strftime("%d/%m/%Y") %></td>
                    <% end %>
                    <td>
                        <%= erp_datalist_row_actions(
                            [
                                {
                                    text: '<i class="fa fa-edit"></i> '+t('.edit'),
                                    href: erp_newsletters.edit_backend_newsletter_path(newsletter)
                                },
                                {
                                    divider: true
                                },
                                {
                                    text: '<i class="fa fa-trash"></i> '+t('.delete'),
                                    url: erp_newsletters.backend_newsletter_path(newsletter),
                                    data_method: 'DELETE',
                                    class: 'ajax-link',
                                    data_confirm: t('.delete_confirm')
                                }
                            ]
                        ) %>
                    </td>
                </tr>            
            <% end %>
        </tbody>
    </table>
    <% if @newsletters.empty? %>
        <div class="datalist-empty-line"><%= t('.no_matching_records_found') %></div>
    <% end %>
</div>
        
<%= erp_datalist_pagination(@newsletters) %>

app/views/erp/newsletters/backend/newsletters/new.html.erb
<h1>New Newsletter</h1>

<%= render 'form', newsletter: @newsletter %>

<%= link_to 'Back', newsletters_path %>

app/views/erp/newsletters/overrides/_backend_newsletters_link_to_sidebar_menu.html.erb
<li class="nav-item <%= "active open" if ["erp/newsletters/backend/newsletters"].include?(params[:controller]) %>">
    <a href="javascript:;" class="nav-link nav-toggle">
        <i class="icon icon-envelope-letter"></i>
        <span class="title"><%= t('.newsletter') %></span>
        <% if ["erp/articles/backend/newsletters"].include?(params[:controller]) %>
            <span class="selected"></span>
            <span class="arrow open"></span>
        <% else %>
            <span class="arrow"></span>
        <% end %>
    </a>
    <ul class="sub-menu">
        <li class="nav-item">
            <a href="<%= erp_newsletters.backend_newsletters_path %>" class="nav-link">
                <span class="title"><%= t('.newsletters') %></span>
            </a>
        </li>
    </ul>
</li>